version: "3.9"

services:
  mongo.db:
    container_name: mongo_chats
    image: mongo:3.6
    command: mongod --maxConns 10000
    volumes:
      - mongo:/data/db
      - ./config/storages/migrations/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

volumes:
  mongo: